# Generated by Django 5.1.6 on 2025-03-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_rename_cardmodel_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
