# Generated by Django 5.1.6 on 2025-03-28 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_remove_cardmodel_deck_id'),
        ('decks', '0002_deck_delete_deckmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decks.deck'),
        ),
        migrations.DeleteModel(
            name='CardModel',
        ),
    ]
