# Generated by Django 5.1.6 on 2025-03-08 15:33
from django.db import migrations

def fill_db(apps, schema_editor):
    cards = apps.get_model('cards', 'Card')
    decks = apps.get_model('decks', 'Deck')
    eng = open('nature_eng.txt', 'r')
    ru = open('nature_ru.txt', 'r')
    length = len(eng.readlines())
    eng.seek(0)
    for i in range(length):
        b_text, desc = ru.readline().split(" - ")
        cards.objects.create(deck_id = decks.objects.get(deck_name = "Nature"), front_text = eng.readline(),
                             back_text = b_text, description = desc)



class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_card_card_id'),
        ('decks', '0003_alter_deck_deck_id')
    ]

    operations = [
        migrations.RunPython(fill_db)
    ]
