# Generated by Django 5.1.6 on 2025-03-08 16:07

from django.db import migrations
import os

def fill_db(apps, schema_editor):
    cards = apps.get_model('cards', 'Card')
    decks = apps.get_model('decks', 'Deck')
    path = os.path.dirname(__file__)
    eng = open(path+'/nature_eng.txt', 'r')
    ru = open(path+'/nature_ru.txt', 'r', encoding='utf-8')
    length = len(eng.readlines())
    eng.seek(0)
    for i in range(length):
        b_text, desc = ru.readline().split(" - ")
        cards.objects.create(deck_id = decks.objects.get(deck_name = "Nature"), front_text = eng.readline(),
                             back_text = b_text, example_usage = desc)
    eng.close()
    ru.close()

class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20250308_1933'),
        ('decks', '0003_alter_deck_deck_id')
    ]

    operations = [
        migrations.RunPython(fill_db)
    ]
