# Generated by Django 5.1.6 on 2025-03-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeckModel',
            fields=[
                ('deck_id', models.IntegerField(primary_key=True, serialize=False)),
                ('deck_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
