# Generated by Django 5.1.6 on 2025-03-07 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_rename_cardmodel_card'),
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeckModel',
            new_name='Deck',
        ),
    ]
