# Generated by Django 5.1.6 on 2025-03-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_remove_cardmodel_deck_id'),
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Колода',
                'verbose_name_plural': 'Колоды',
            },
        ),
        migrations.DeleteModel(
            name='DeckModel',
        ),
    ]
