# Generated by Django 5.1.6 on 2025-03-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_rename_deckmodel_deck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='deck_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
