# Generated by Django 5.1.6 on 2025-03-28 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_deck_delete_deckmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='deck_name',
            new_name='name',
        ),
    ]
