# Generated by Django 5.1.6 on 2025-05-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0003_rename_deck_name_deck_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='cover',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
