# Generated by Django 5.1.6 on 2025-05-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0005_alter_deck_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='cover',
            field=models.ImageField(upload_to='decks/static/'),
        ),
    ]
